name: vpapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.4 # Http Client
  intl: ^0.17.0 # Date Formater
  hive: ^2.0.5 # Local Data Storage
  hive_flutter: ^1.1.0 # Local Data Storage
  provider: ^6.0.2 # Global State Management Solution
  go_router: ^3.0.1 # Router
  url_launcher: ^6.0.20 # URL Launcher
  flutter_html: ^2.2.1 # HTML Renderer
  path_provider: ^2.0.9 # Path Provider
  infinite_scroll_pagination: ^3.1.0 # Pageinated List/Grid
  
  # Dio Plugins
  cookie_jar: ^3.0.1 # Store Cookies
  dio_cookie_manager: ^2.0.0 # Cookie Manager
  dio_cache_interceptor: ^3.2.5 # Cache Interceptor
  dio_cache_interceptor_hive_store: ^3.1.1 # Hive Cache Store

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
